<?php $this->headTitle('Sags mit Video') ?>
<!-- Video intro-video -->
<script type="application/javascript">
    var autoplay = "<?= $this->autoplay ?>";
</script>
<div class="section green-bg hidden-xs" id="first-section">
    <div id="intro-video-container">
        <video class="visible-xs" id="intro-video-xs" poster="/video/Nemuk_Showreel-HD.jpg" src="">
        </video>
        <video class="visible-sm" id="intro-video-sm" poster="/video/Nemuk_Showreel-HD.jpg" src="">
        </video>
        <video class="visible-md visible-lg" id="intro-video" muted="muted" poster="/video/Nemuk_Showreel-HD.jpg" <?=
        $this->autoplay == 'off' ? '' : ' autoplay="autoplay" ' ?>
               src="">
        </video>

        <div id="intro-video-gradient"></div>

        <span id="intro-play-2"
              class="streamline-120px red icon-play-2 hidden-xs <?= $this->autoplay == 'on' ? ' hidden' : '' ?>"
              onclick=""></span>


        <div class="text-center" id="video-overlay">
            <h1 class="white">Nemuk.</h1>

            <h2 class="subtitle green">Wir machen Ihr Video</h2>

            <h3 class="subtitle no-margin">
                <a class="yellow" href="#why-onlinevideo">
                    Erfahren Sie, wie <br/>
                    <span class="glyphicon glyphicon-chevron-down"></span>
                </a>
            </h3>

            <div id="video-control" <?= $this->autoplay == 'off' ? ' class="hidden"' : '' ?>>
                  <span class="streamline-60px red yellow icon-volume-mute-1 hidden-xs"
                        onclick="document.getElementById('intro-video').muted=true"></span>
                  <span class="streamline-60px red yellow icon-volume-medium-1 hidden-xs"
                        onclick="document.getElementById('intro-video').muted=false"></span>
            </div>
        </div>
    </div>
</div>

<!-- 1 Sags mit Video -->
<div class="section green-bg" id="why-onlinevideo">
    <div class="container">
        <div class="row">
            <div class="text-center visible-xs">
                <video width="100%" src="/video/Showreel+All+Styles-Mobil.mp4" controls="controls"></video>
            </div>
            <div class="spacer-6em"></div>
            <div class="col-md-12 text-center">
                <h1 class="thin" style="padding-bottom: 60px;"><?= $this->translate('Sags mit Video') ?></h1>
            </div>
            <div class="col-md-4 text-center">
                <span class="streamline-120px red icon-bubble-conversation-5"></span>

                <h3><a class="underline black"
                       href="/index/your-benefits"><?= $this->translate('Mehr Bekanntheit') ?></a></h3>

                <p>5 Facts, wieso Sie mit Videos besser in Erinnerung bleiben.</p>
            </div>
            <div class="col-md-4 text-center">
                <span class="streamline-120px red icon-transfer-12"></span>

                <h3><a class="underline black"
                       href="/index/your-benefits#more-traffic"><?= $this->translate('Mehr Traffic') ?>
                        (SEO)</a></h3>

                <p>3 Tricks, wie Sie dank Videos deutlich bessere Klickraten auf Ihrer Page erzielen.</p>
            </div>
            <div class="col-md-4 text-center">
                <span class="streamline-120px red icon-chart-up "></span>

                <h3><a class="underline black"
                       href="/index/your-benefits#more-sale"><?= $this->translate('Mehr Verkaufserfolg') ?></a>
                </h3>

                <p>6 Tipps, wie Sie mit Videos Ihr Unternehmen und Ihre Produkte nach aussen und innen besser
                    verkaufen.</p>
            </div>
        </div>
    </div>
</div>

<!-- 2 Nemuk Video -->
<div class="section yellow-bg">
    <div class="container">
        <div class="row">
            <!-- left -->
            <div class="col-md-6">
                <h1 class="thin">Nemuk.</h1>

                <p class="subtitle green">Ihr Partner für Video</p>

                <p class="lead">Nach über 100 Videos für bekannte Brands wie Swisscom, SBB, Suva, Swissaid, WWF etc.
                    gelten wir als zuverlässige Adresse unter den Schweizer Video-Machern.</p>

                <p class="subtitle">
                    <a href="/index/about" class="underline black"><?= $this->translate('Über uns') ?></a>
                </p>

                <div class="spacer"></div>
            </div>

            <!-- right -->
            <div class="col-md-6">
                <div class="row">
                    <div class="spacer"></div>
                    <div class="col-md-1"></div>
                    <div class="col-xs-3">
                        <span class="streamline-90px red icon-palette "></span>
                    </div>
                    <div class="col-xs-8">
                        <h3><?= $this->translate('individuell') ?></h3>

                        <p>Vielfältige Ausdrucksmöglichkeiten dank den besten Partnern und Spezialisten.</p>
                    </div>
                </div>
                <div class="row">
                    <div class="spacer"></div>
                    <div class="col-md-1"></div>
                    <div class="col-xs-3">
                        <span class="streamline-90px red icon-calculator-2 "></span>
                    </div>
                    <div class="col-xs-8">
                        <div>
                            <h3><?= $this->translate('preisgünstig') ?></h3>

                            <p>Moderne Ausrüstung und effiziente Arbeitsabläufe erlauben Top-Filme auch für kleine
                                Budgets.</p>
                        </div>
                        <div class="spacer"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="spacer"></div>
                    <div class="col-md-1"></div>
                    <div class="col-xs-3">
                        <span class="streamline-90px red icon-location "></span>
                    </div>
                    <div class="col-xs-8">
                        <div>
                            <h3><?= $this->translate('kompetent') ?></h3>

                            <p>Ob Grossunternehmen, KMU oder NGO – dank unserer breiten Erfahrung finden wir die
                                richtige Sprache.</p>
                        </div>
                        <div class="spacer"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- 3 Videostile -->
<div class="section green-bg">
    <div class="container">

        <div class="row">
            <div class="col-md-12 text-center">
                <h1 class="thin"><?= $this->translate('Die Videostile') ?></h1>

                <div class="spacer-6em"></div>
            </div>
        </div>

        <div class="row video-style">
            <div class="col-md-6">
                <div class="video-container">
                    <img class="video-placeholder shadow" width="100%" src="/video/Simplify_479000206_1280.jpg"
                         alt="Simplify Erklärvideo Standbild"/>
                    <img class="video-placeholder" width="100%" src="/video/Play.png" alt="playbutton"/>
                    <iframe class="hidden shadow"
                            url="//player.vimeo.com/video/95869954?autoplay=1;title=0&amp;byline=0&amp;portrait=0&amp;color=ffffff"
                            width="100%" height="310" frameborder="0" webkitallowfullscreen mozallowfullscreen
                            allowfullscreen></iframe>
                </div>
                <h4 class="text-center subtitle video-legend">
                    <a href="/index/video-styles/simplify"
                       class="underline black"><?= $this->translate('Simplify Erklärvideo') ?></a>
                </h4>
            </div>

            <div class="col-md-6">
                <div class="video-container">
                    <img class="video-placeholder shadow" width="100%"
                         src="/video/Animation_MotionGraphics_479006329_1280.jpg"
                         alt="Standbild Animation und Motion Graphics"/>
                    <img class="video-placeholder" width="100%" src="/video/Play.png" alt="playbutton"/>
                    <iframe class="hidden shadow"
                            url="//player.vimeo.com/video/96589106?autoplay=1;title=0&amp;byline=0&amp;portrait=0&amp;color=ffffff"
                            width="100%" height="310" frameborder="0" webkitallowfullscreen mozallowfullscreen
                            allowfullscreen></iframe>
                </div>
                <h4 class="text-center subtitle video-legend">
                    <a href="/index/video-styles/animation-mg"
                       class="underline black"><?= $this->translate('Animation und Motion Graphics') ?></a>
                </h4>
            </div>

            <div class="col-md-6">
                <div class="video-container">
                    <img class="video-placeholder shadow" width="100%" src="/video/Realfilm_479006803_1280.jpg"
                         alt="Realfilm Standbild"/>
                    <img class="video-placeholder" width="100%" src="/video/Play.png" alt="playbutton"/>
                    <iframe class="hidden shadow"
                            url="//player.vimeo.com/video/99020222?autoplay=1;title=0&amp;byline=0&amp;portrait=0&amp;color=ffffff"
                            width="100%" height="310" frameborder="0" webkitallowfullscreen mozallowfullscreen
                            allowfullscreen></iframe>
                </div>
                <h4 class="text-center subtitle video-legend">
                    <a href="/index/video-styles/real"
                       class="underline black"><?= $this->translate('Realfilm') ?></a>
                </h4>
            </div>

            <div class="col-md-6">
                <div class="video-container">
                    <img class="video-placeholder shadow" width="100%"
                         src="/video/Animation_Real_479006568_1280.jpg"
                         alt="Animation und Realfilm Standbild"/>
                    <img class="video-placeholder" width="100%" src="/video/Play.png" alt="playbutton"/>
                    <iframe class="hidden shadow"
                            url="//player.vimeo.com/video/99019888?autoplay=1;title=0&amp;byline=0&amp;portrait=0&amp;color=ffffff"
                            width="100%" height="310" frameborder="0" webkitallowfullscreen mozallowfullscreen
                            allowfullscreen></iframe>
                </div>
                <h4 class="text-center subtitle video-legend">
                    <a href="/index/video-styles/animation-real"
                       class="underline black"><?= $this->translate('Animation und Realfilm') ?></a>
                </h4>
            </div>
        </div>
        <!-- row -->
    </div>
    <!-- container -->
</div>

<!-- Testimonials -->
<div class="section yellow-bg">
    <div class="container big-padding">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1 class="thin">«Ihr habt es mal wieder geschafft!»</h1>
                <h4 class="subtitle green">Über 100 Videos und viele glückliche Kunden.</h4>
            </div>
        </div>


        <div class="row" id="testimonial1">
            <div class="testimonial-container">
                <span class="streamline-60px icon-arrow-67 testimonial-switch test3nav green"></span>

                <div class="testimonial-cell">
                    <p class="red text-left quotation-mark">”</p>

                    <p class="lead text-left testimonial">„Vielen Dank für die Produktion unseres internen HR-Videos.
                        Ihr habt es mal wieder geschafft, dass der thematische Prozess zu einem sinnvollen und einfach
                        verständlichen Ganzen kommt.“</p>

                    <p class="text-right">— Mirjam Birrer, <strong>SUVA</strong></p>
                </div>
                <span class="streamline-60px icon-arrow-68 testimonial-switch test2nav green"></span>
            </div>
        </div>


        <div class="row" id="testimonial2">
            <div class="testimonial-container">
                <span class="streamline-60px icon-arrow-67 testimonial-switch test1nav green"></span>

                <div class="testimonial-cell">
                    <p class="red text-left quotation-mark">”</p>

                    <p class="lead text-left testimonial">„Vielen Dank für die gute und unkomplizierte Zusammenarbeit.
                        Die Videos kommen gut an und die Rückmeldungen sind durchwegs positiv.“</p>

                    <p class="text-right">— Martin König, <strong>SBB</strong></p>
                </div>
                <span class="streamline-60px icon-arrow-68 testimonial-switch test3nav green"></span>
            </div>
        </div>


        <div class="row" id="testimonial3">
            <div class="testimonial-container">
                <span class="streamline-60px icon-arrow-67 testimonial-switch test2nav green"></span>

                <div class="testimonial-cell">
                    <p class="red text-left quotation-mark">”</p>

                    <p class="lead text-left testimonial">„Die Zusammenarbeit war sehr angenehm, lehrreich und hat Spass
                        gemacht. Gerne kommen wir wieder auf Euch zu, wenn wir weitere Themen einfach als Videos erklärt
                        haben möchten.“</p>

                    <p class="text-right">— Eliane Baumgartner, <strong>Swissaid</strong></p>
                </div>
                <span class="streamline-60px icon-arrow-68 testimonial-switch test1nav green"></span>
            </div>
        </div>


        <div class="row">
            <div class="col-md-12 text-center">
                <div class="spacer-6em"></div>
                <h4 class="subtitle "><a class="black underline" href="/index/references">
                        <?= $this->translate('Empfehlungen und Referenzen') ?></a></h4>
            </div>
        </div>
    </div>
</div>


<div class="section green-bg pattern-bg">
    <div class="container big-padding">
        <div class="row">
            <div class="col-md-12 text-center">
                <h4 class="subtitle "><a class="black underline" href="/offer">
                        <?= $this->translate('Stellen Sie Ihr eigenes Video zusammen') ?></a></h4>
            </div>
        </div>
    </div>
</div>

